### ISSUE TITLE
dnPl allocates even when using a cache

### ISSUE THREAD

**Issue by HMegh** [jishnub/LegendrePolynomials.jl#23]
Hi, 

In the current version, `dnPl(x,l,n,A)` seems to be allocating memory when used frequently. For example,

```julia
A=zeros(30,10);cache=zeros(10)
function with_cache!(A,cache) 
   @assert size(A,2)==10
   n=size(A,1) 
   for i=1:n,j=1:10
       x=-1+2i/n
       A[i,j]=dnPl(x,j,4,cache)
   end 
   A 
end
@btime with_cache!(A,cache)
 # 19.663 μs (270 allocations: 4.22 KiB)
```
See the following discussion on [Discourse](https://discourse.julialang.org/t/what-is-the-best-way-to-re-use-a-temporary-vector/121519), it appears that changing `doublefactorial(T, n)` to  `doublefactorial(::Type{T}, n)` fixes this issue and improves the performance. Here's the new benchmark result
```julia-repl
julia> @btime with_cache!(A,cache)
  7.140 μs (0 allocations: 0 bytes)
```

I will submit a PR shortly.

**Comment by jishnub** [comment]
Closed by #24
