### ISSUE TITLE
Specify norm used in the Legendre polynomials

### ISSUE THREAD

**Issue by philipbergander** [jishnub/LegendrePolynomials.jl#9]
Coming from Matlab I was uncertain which norm is used in this package, since Matlab allows 3 norms: 

1. No normalization
2. Schmidt seminormalized
3. Fully normalized

I figured out the normalization used in Julia by calling `Plm` and comparing the result to Matlab (no normalization is used), but it may be useful to have it specified in print.

**Comment by jishnub** [comment]
It will be useful to support multiple normalization options as well
